### ISSUE TITLE
Could you please add supprot for Android 10?

### ISSUE THREAD

**Issue by ameaninglessname** [congshengwu/Xposed_Clipboard#1]
It seems not working on android 10.

Device : oneplus 5T
ROM : Pixel Experience 10 0106

**Comment by congshengwu** [comment]
Hi @RemRemRemRe, thank you for your attention, I will have a look this weekend, and give you an answer later.

**Comment by ameaninglessname** [comment]
> 
> 
> Hi @RemRemRemRe, thank you for your attention, I will have a look this weekend, and give you an answer later.

谢谢大佬

**Comment by ameaninglessname** [comment]
🥺小的来催更了

**Comment by klcb2010** [comment]
看来安卓10无望了😳

**Comment by ameaninglessname** [comment]
> 
> 
> 看来安卓10无望了😳

安卓10上可以用，我用的无极

**Comment by congshengwu** [comment]
@RemRemRemRe 
实在抱歉，这段时间太忙了，一直在搬砖，没有及时的去调研。~。~
还有一点，我身边没有运行安卓10的手机，我只有一加5，运行的H2OS (没刷别的ROM)，安卓11都要来了，张老板还一直没给咱推送安卓10。

**Comment by ameaninglessname** [comment]
> 
> 
> @RemRemRemRe
> 实在抱歉，这段时间太忙了，一直在搬砖，没有及时的去调研。~。~
> 还有一点，我身边没有运行安卓10的手机，我只有一加5，运行的H2OS (没刷别的ROM)，安卓11都要来了，张老板还一直没给咱推送安卓10。

没事，您不需要说抱歉的，本来就是开源项目。

而且我这边可以正常使用的。
